### ISSUE TITLE
SDL does not seem to handle screen orientation properly

### ISSUE THREAD

**Issue by misha-franz** [MikuAuahDark/livesim3-love-android#3]
Not sure this issue is on your side, just want this to be documented somewhere.

Noticed that what I set screen orientation in the manifest to portrait the app still appears landscape.

Found the following function in SDL_androidwindow.c and maid a quick change which seems to help.  Looks like otherwise SDL assumes the screen is w=800, h=600, makes assumption that it should be landscape and only then gets the actual screen dimensions. Agree?

See inline

int
Android_CreateWindow(_THIS, SDL_Window * window)
{
    SDL_WindowData *data;
    
    if (Android_Window) {
        return SDL_SetError("Android only supports one window");
    }
    
    Android_PauseSem = SDL_CreateSemaphore(0);
    Android_ResumeSem = SDL_CreateSemaphore(0);

    /* Set orientation */
    // Moved this
    // Android_JNI_SetOrientation(window->w, window->h, window->flags & SDL_WINDOW_RESIZABLE, SDL_GetHint(SDL_HINT_ORIENTATIONS));

    /* Adjust the window data to match the screen */
    window->x = 0;
    window->y = 0;
    window->w = Android_SurfaceWidth;
    window->h = Android_SurfaceHeight;

    // To here (not sure if this is the correct fix or place, but now the window appears portrait it set so in the manifest)
    Android_JNI_SetOrientation(window->w, window->h, window->flags & SDL_WINDOW_RESIZABLE, SDL_GetHint(SDL_HINT_ORIENTATIONS));

    window->flags &= ~SDL_WINDOW_RESIZABLE;     /* window is NEVER resizeable */
    window->flags &= ~SDL_WINDOW_HIDDEN;
    window->flags |= SDL_WINDOW_SHOWN;          /* only one window on Android */
    window->flags |= SDL_WINDOW_INPUT_FOCUS;    /* always has input focus */

    /* One window, it always has focus */
    SDL_SetMouseFocus(window);
    SDL_SetKeyboardFocus(window);
    
    data = (SDL_WindowData *) SDL_calloc(1, sizeof(*data));
    if (!data) {
        return SDL_OutOfMemory();
    }
    
    data->native_window = Android_JNI_GetNativeWindow();
    
    if (!data->native_window) {
        SDL_free(data);
        return SDL_SetError("Could not fetch native window");
    }

    /* Do not create EGLSurface for Vulkan window since it will then make the window
       incompatible with vkCreateAndroidSurfaceKHR */
    if ((window->flags & SDL_WINDOW_VULKAN) == 0) {
        data->egl_surface = SDL_EGL_CreateSurface(_this, (NativeWindowType) data->native_window);

        if (data->egl_surface == EGL_NO_SURFACE) {
            ANativeWindow_release(data->native_window);
            SDL_free(data);
            return SDL_SetError("Could not create GLES window surface");
        }
    }

    window->driverdata = data;
    Android_Window = window;
    
    return 0;
}

**Comment by MikuAuahDark** [comment]
In your conf.lua, do you set the window dimension to portrait dimension too? like 768x1024

**Comment by misha-franz** [comment]
No, I do not. Should I? I assumed in Android it should learn the orientation from the manifest. Also I prefer to set max possible resolution instead of guessing one. But maybe I miss something.

Here is what I do in love.load():

love.window.setFullscreen(true)
local w, h = love.graphics.getDimensions()

**Comment by MikuAuahDark** [comment]
I think you can set the orientation with `SDL_Hint`, please see [this](https://wiki.libsdl.org/SDL_HINT_ORIENTATIONS). I think it's good to have this functionality in LOVE.

**Comment by misha-franz** [comment]
The following code seems to help, but the screen still starts in landscape and then switches to portrait, which looks ugly. Behaves the same regardless what is set in the manifest.

  love.window.setFullscreen(true)
  local w, h = love.graphics.getDimensions()
  if w > h then
    w, h = h, w
  end
  love.window.setMode(w, h)

**Comment by MikuAuahDark** [comment]
You can try to flip the window dimensions in conf.lua and see if that helps.

Pada tanggal Kam, 31 Jan 2019 09.50, misha-franz <notifications@github.com>
menulis:

**Comment by misha-franz** [comment]
Thanks! Indeed the following works just fine:

Manifest:
android:screenOrientation="portrait"

conf.lua:
function love.conf(t)
  t.window.width = 600
  t.window.height = 800
end

main.lua:
function love.load()
  love.window.setFullscreen(true)
  local w, h = love.graphics.getDimensions()
  ...

**Comment by misha-franz** [comment]
FYI noticed that at least on Essential

love.window.setFullscreen(true)
local w, h = love.graphics.getDimensions()

sometimes gets real screen dimensions and sometimes something smaller (likely without the notch). Doing nothing else but opening app, closing, and opening again. About 20% of times, wrong screen height.

After changing:

int
Android_CreateWindow(_THIS, SDL_Window * window) 

    //window->w = Android_SurfaceWidth;
    //window->h = Android_SurfaceHeight;

    window->w = Android_DeviceWidth;
    window->h = Android_DeviceHeight;

always returns full screen dimensions.

Puzzled...
