### ISSUE TITLE
getGamePath() body is commented out - the app will not load game.love

### ISSUE THREAD

**Issue by misha-franz** [MikuAuahDark/livesim3-love-android#4]
Noticed that getGamePath() body is commented out and the app could not find game.love is assets. Un-commented and it seems to help.

    public static String getGamePath() {
        GameActivity self = (GameActivity) mSingleton; // use SDL provided one
        Log.d("GameActivity", "called getGamePath(), game path = " + gamePath);

        if (gamePath.length() > 0) {
            if(self.hasExternalStoragePermission()) {
                return gamePath;
            } else {
                Log.d("GameActivity", "cannot open game " + gamePath + ": no external storage permission given!");
            }

        } else {
            self.checkLovegameFolder();
            if (gamePath.length() > 0)
                return gamePath;
        }

        return "";
    }

**Comment by MikuAuahDark** [comment]
The reason it's commented out is because this fork of LOVE is meant for my live simulator.
