### ISSUE TITLE
Crash on start on older devices

### ISSUE THREAD

**Issue by misha-franz** [MikuAuahDark/livesim3-love-android#5]
The app works OK on newer (64bit?) phones like Essential PH-1 (Android 9) or Nokia 6 (Android 8.1).

However it crashed when starts on older devices like Moto E (Android 5.1.1, 32 bit?).

Logcat:

01-28 11:58:05.316 9570-9570/? I/art: Late-enabling -Xcheck:jni
01-28 11:58:05.365 9570-9580/? E/art: Failed sending reply to debugger: Broken pipe
01-28 11:58:05.366 9570-9580/? I/art: Debugger is no longer active
01-28 11:58:05.636 9570-9570/? I/InstantRun: starting instant run server: is main process
01-28 11:58:05.742 9570-9570/? D/GameActivity: started
01-28 11:58:05.875 9570-9570/? D/GameActivity: new gamePath: game.love
01-28 11:58:05.875 9570-9570/? V/SDL: Device: surnia_cdma
01-28 11:58:05.875 9570-9570/? V/SDL: Model: XT1526
01-28 11:58:05.875 9570-9570/? V/SDL: onCreate()
01-28 11:58:05.878 9570-9570/? W/linker: libc++_shared.so: unused DT entry: type 0x6ffffffe arg 0x2bb84
01-28 11:58:05.879 9570-9570/? W/linker: libc++_shared.so: unused DT entry: type 0x6fffffff arg 0x2
01-28 11:58:05.888 9570-9570/? W/linker: libmpg123.so: unused DT entry: type 0x6ffffffe arg 0x37c4
01-28 11:58:05.888 9570-9570/? W/linker: libmpg123.so: unused DT entry: type 0x6fffffff arg 0x3
01-28 11:58:05.894 9570-9570/? W/linker: libopenal.so: unused DT entry: type 0x6ffffffe arg 0x45f8
01-28 11:58:05.894 9570-9570/? W/linker: libopenal.so: unused DT entry: type 0x6fffffff arg 0x3
01-28 11:58:05.919 9570-9570/? E/art: dlopen("/data/app/org.love2d.android-2/lib/arm/libopenal.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__android_log_print" referenced by "libopenal.so"...
01-28 11:58:05.920 9570-9570/? W/System.err: dlopen failed: cannot locate symbol "__android_log_print" referenced by "libopenal.so"...
01-28 11:58:06.024 9570-9589/? D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
01-28 11:58:06.038 9570-9570/? D/Atlas: Validating map...
01-28 11:58:06.054 9570-9570/? E/art: No implementation found for void org.libsdl.app.SDLActivity.nativeSetenv(java.lang.String, java.lang.String) (tried Java_org_libsdl_app_SDLActivity_nativeSetenv and Java_org_libsdl_app_SDLActivity_nativeSetenv__Ljava_lang_String_2Ljava_lang_String_2)
01-28 11:58:06.054 9570-9570/? D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
01-28 11:58:06.056 9570-9570/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.love2d.android, PID: 9570
    java.lang.UnsatisfiedLinkError: No implementation found for void org.libsdl.app.SDLActivity.nativeSetenv(java.lang.String, java.lang.String) (tried Java_org_libsdl_app_SDLActivity_nativeSetenv and Java_org_libsdl_app_SDLActivity_nativeSetenv__Ljava_lang_String_2Ljava_lang_String_2)
        at org.libsdl.app.SDLActivity.nativeSetenv(Native Method)
        at org.love2d.android.GameActivity.onCreate(GameActivity.java:97)
        at android.app.Activity.performCreate(Activity.java:6010)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
        at android.app.ActivityThread.access$800(ActivityThread.java:155)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5343)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
01-28 11:58:09.161 9570-9570/org.love2d.android I/Process: Sending signal. PID: 9570 SIG: 9

**Comment by MikuAuahDark** [comment]
I think this is why it crash when I tried it in emulator. I already have proper fix in mind but I don't have access to laptop atm.

**Comment by MikuAuahDark** [comment]
Can you please try the latest commit?

**Comment by misha-franz** [comment]
Just tried. Does not crash on Moto E. Will try more devices later today. Thanks for the fix.

**Comment by misha-franz** [comment]
Briefly tested also on Essential PH1, Pixel 3 XL and Nokia 6. All seem to work OK. Tried installing on Kyocera Hydro Reach 5.1.1 - failed to install (also cannot find drivers for this phone) - weird phone, ignore.

**Comment by MikuAuahDark** [comment]
Also tried it on my emulator, x86 through libhoudini, Android 5.1, no crashes either. So I think everything is good.

**Comment by misha-franz** [comment]
Thanks. BTW do you think it makes sense to support Intel in the app? Some tablets are Intel based, also Chromebooks have Play Store support...

**Comment by MikuAuahDark** [comment]
It was supposed to support Intel devices at some point but I dropped it
because the size increase is not worth it. Should not be hard to add
support for it by adding prebuilt x86 binaries (oals, freetype, ...) and
tell gradle to build for x86.

Pada tanggal Kam, 31 Jan 2019 07.58, misha-franz <notifications@github.com>
menulis:
