### ISSUE TITLE
Squares instead of digits when score is printf-ed while app is on background

### ISSUE THREAD

**Issue by misha-franz** [MikuAuahDark/livesim3-love-android#6]
Hi

When game is over on the background and I show score, quite often (not always) when returning to the app, it looks like on the picture: https://photos.app.goo.gl/EmHp9ytzFBWngK1b6

If the game if over and the app is active it looks normal: https://photos.app.goo.gl/nTSqb2qA4myQ4WH17

This seem to happen on newer Android versions (9, 7), at least I did not notice on 5.1.1 even once, though need to test more.

Tried several different fonts with same results.

Any ideas?

Thanks,
Michael.

**Comment by MikuAuahDark** [comment]
The only reason I can think of why is that the fonts gets rendered into premultiplied alpha.

**Comment by MikuAuahDark** [comment]
Closed due to inactivity.
